startupweekend_index:
    pattern:  /
    defaults:
        _controller: startupweekend.contentful.controller.page:pageAction
        template:    'FoundershubStartupWeekendBundle:Page:index.html.twig'

startupweekend_blogpost:
    pattern:  /blog/{slug}
    defaults:
        _controller: startupweekend.contentful.controller.page:pageAction
        template:    'FoundershubStartupWeekendBundle:Page:blog.html.twig'

# Twitter stream
startupweekend_twitter_stream:
    path: /api/tweets
    defaults:
        _controller: foundershub.startupweekend.controller.twitter:twitterAction
        _format: json
